<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    protected $table = 'reviews';

    public static function getAll()
    {
        return self::orderBy('status')->orderBy('created_at', 'desc')->get();
    }

    public static function getAllSite()
    {
        return self::where('product_id', 0)->where('status', 1)
            ->orderBy('date', 'desc')->get();
    }

    public static function deleteById($id)
    {
        return self::where('id', $id)->delete();
    }

    public static function changeStatusById($id)
    {
        return self::whereId($id)->first()->switchStatus()->update();
    }

    /**
     * @return int count of reviews which has status non publicated
     */
    public static function noneActivated()
    {
        return self::where('status', 0)->count();
    }

    public static function create(array $attributes = [])
    {
//        dd($attributes);
        return self::insert($attributes); // TODO: Change the autogenerated stub
    }

    public function switchStatus()
    {
        $this->status = ($this->status)? 0 : 1;
        return $this;
    }
}
